a = complex(5, 8)
b = complex(4, -7)
print("Sean 2 numeros complejos a: ", a)
print("y b: ", b)
print("\nLa suma es ", a+b)
print("\nEl producto es ", a*b)
print("\nLa parte real de a es ", a.real)
print("\nLa magnitud del complejo a es ", abs(a))
print("\nEl complejo conjugado es ", a.conjugate())